im in github and trying to create page using this project but i get this error:
16s
Run npx --no-install next build
⚠ No build cache found. Please configure build caching for faster rebuilds. Read more: https://nextjs.org/docs/messages/no-cache
Attention: Next.js now collects completely anonymous telemetry regarding usage.
This information is used to shape Next.js' roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
https://nextjs.org/telemetry

   ▲ Next.js 15.2.3

   Creating an optimized production build ...

Retrying 1/3...

Retrying 1/3...

Retrying 1/3...

Retrying 1/3...

Retrying 1/3...

Retrying 1/3...
 ✓ Compiled successfully
   Linting and checking validity of types ...
Failed to compile.

./src/app/page.tsx:592:61
Type error: This comparison appears to be unintentional because the types '"asking_verb" | "asking_subject" | "feedback_incorrect_verb" | "feedback_incorrect_subject"' and '"loading"' have no overlap.

  590 |                   size="lg"
  591 |                   onClick={handleSubmit}
> 592 |                   disabled={selectedIndices.length === 0 || status === 'loading' || status === 'initial_loading'}
      |                                                             ^
  593 |                   className="w-full sm:w-auto text-xl sm:text-2xl md:text-3xl px-8 py-4 sm:px-10 sm:py-5 md:px-12 md:py-6 rounded-xl shadow-lg transform hover:scale-105 transition-transform duration-200"
  594 |                 >
  595 |                   Valider
Next.js build worker exited with code: 1 and signal: null
Error: Process completed with exit code 1.